In [4]:
from ortools.linear_solver import pywraplp
import numpy

#  n  > 30
# |m| > 1 + |n|
# |q| > |m|

n = 4
m = 16
q = 37

def SVP(m,n,q):
    solver = pywraplp.Solver.CreateSolver('SCIP')
    L = numpy.random.randint(-(q-1)/2, (q-1)/2, (m, n))
    e = {}
    k = {}
    #e é um vetor de tamanho m com valores inteiros -1, 0 ou 1
    for j in range(m):
        e[j] = [solver.BoolVar('e[%i][-1]' % j),
                solver.BoolVar('e[%i][0]' % j),
                solver.BoolVar('e[%i][1]' % j)]
        #e só pode ter um elemento por cada j
        solver.Add(e[j][0] + e[j][1] + e[j][2] == 1)
    
            
    #k é um vetor de tamanho n com valores inteiros
    for i in range(n):
        k[i] = solver.IntVar(-solver.infinity(), solver.infinity(), 'k[%i]' % i)
    
    #Tem de existir um elemento não nulo em e
    solver.Add(sum([e[j][1] for j in range(m)]) <= m-1)
    
    #Multiplicar e por L deve resultar num vetor de múltiplos de q
    for i in range(n):
        solver.Add((sum([(e[j][2] - e[j][0])*L[j][i] for j in range(m)])) == q * k[i])
    
    solver.Maximize(sum([e[j][1] for j in range(m)]))
    status = solver.Solve()
    if status == pywraplp.Solver.OPTIMAL:
        print(L)
        print("")
        for i in range(n):
            print(k[i].solution_value())
        print("")
        for j in range(m):
            for k in range(3):
                if e[j][k].solution_value():
                    print(k-1)
    else:
        print(L)
        print("")
        for i in range(n):
            print(k[i].solution_value())
        print("")
        for j in range(m):
            for k in range(3):
                if e[j][k].solution_value():
                    print(k-1)
        print("Não é possível resolver o problema")
    
SVP(m,n,q)

[[ 10   7 -18   7]
 [ 16  -7   0  -9]
 [  6  -3  -8   3]
 [ -2 -14 -11  17]
 [-18  -9  17   0]
 [  9  17 -10  17]
 [ 14 -14  17 -18]
 [ -2  -4  -8  -5]
 [  5 -13   4  13]
 [ -8  -1   0 -11]
 [ 12  10  -7   7]
 [ -5   2  17  16]
 [ 17  -3 -11   0]
 [ -7 -13  15  -6]
 [ -9 -10 -17  11]
 [ -2   1  17   1]]

1.0
-1.0
-2.0
0.0

1
0
0
1
0
0
1
0
0
0
0
-1
1
0
1
-1
