In [16]:
from ortools.linear_solver import pywraplp
import numpy

#  n  > 30
# |m| > 1 + |n|
# |q| > |m|

n = 31
m = 64
q = 131

def SVP(m,n,q):
    solver = pywraplp.Solver.CreateSolver('SCIP')
    L = numpy.random.randint(-(q-1)/2, (q-1)/2, (m, n))
    print(L)
    e = {}
    #e é um vetor de tamanho m com valores inteiros -1, 0 ou 1
    for i in range(m):
        e[i] = solver.IntVar(-1,1,'e[%i]' % i)
    #print(e)
    
    #Tem de existir um elemento não nulo em e
    solver.Add(sum([abs(e[j]) for j in range(m)]) > 0)
    
    #Multiplicar e por L deve resultar num vetor de múltiplos de q
    for i in range(n):
        solver.Add((sum([e[j] * L[j][i] for j in range(m)]) % q) == 0)
    
SVP(m,n,q)

[[ 18 -15 -13 ...  39 -46  16]
 [-33  26   6 ...  -7 -58  31]
 [ 59 -15  19 ... -22   6 -63]
 ...
 [-55  32  33 ...  20 -51 -64]
 [ 39  46 -63 ...  14 -58 -42]
 [-29 -56  39 ...  43  22   3]]


TypeError: bad operand type for abs(): 'Variable'