# TP1 - Grupo 14

André Lucena Ribas Ferreira - A94956

Paulo André Alegre Pinto - A97391

## Problema 2 - Cálculo do SVP

Na criptografia pós-quântica os reticulados inteiros (“hard lattices”) e os problemas a eles associados são uma componente essencial. Um reticulado inteiro pode ser definido por uma matriz $L \in \mathbb{Z}^{m\times n}$ (com $m > n$) de inteiros e por um inteiro primo $q \geq 3$.

Como 'inputs', o problema recebe:
1. Número natural $n$;
2. Número natural $m$, tal que $|m| > |n| + 1$;
3. Número natural primo $q$, tal que $|q| > |m|$.
4. Os elementos $L_{j,i}$ são gerados aleatória e uniformemente no intervalo inteiro $\{-d, \cdots, d\}$ sendo  $d = (q-1)/2$.

O chamado problema do vetor curto (SVP) consiste no cálculo de um vetor de inteiros: $e\in \{-1,0,1\}^m$
não nulo que verifique a seguinte relação matricial:
$$\forall_{i < n}, \quad (\sum_{j< m} e_j \times \mathsf{L}_{j,i}) \equiv 0 \mod q$$


### Análise

Para resolver o problema do SVP, decidimos usar duas famílias de variáveis, uma binária e outra inteira.

A família de variáveis binárias $e_{j,l}$ é definida com a seguinte semântica, para $l \in \{0,1,2\}$ e $0 <= j < m$:

$$e_{j,0} == 1 \quad \mbox{se e só se} \quad e[j] == -1$$
$$e_{j,1} == 1 \quad \mbox{se e só se} \quad e[j] == 0$$
$$e_{j,2} == 1 \quad \mbox{se e só se} \quad e[j] == 1$$

A família de variáveis inteiras $k_{i}$, para $i < n$ servirá para conseguir iterar pelos números inteiros, de modo a se encontrar os múltiplos de $q$ para cada resultado da multiplicação entre $e$ e $L$.

O problema dispõe de restrições que deverão ser tratadas:

1. Para cada posição $j < m$ de $e$, $e[j]$ só admite um único valor;
2. Pelo menos um elemento de $e$ tem de ser não nulo;
3. Multiplicar o vetor $e$ pela matriz $L$ deve resultar num vetor de múltiplos de $q$.

Do mesmo modo, o problema admite a seguinte optimização:

1. Maximizar o número de componentes nulas de $e$.

## Implementação

Para a resolução do problema, utilizaremos a biblioteca de programação linear do $OR-Tools$, o $pywraplp$. Portanto, começamos por instalar o OR-Tools, importar a biblioteca e inicializar o $solver$, que chamaremos de 'solver'.

In [1]:
!pip install ortools

In [2]:
from ortools.linear_solver import pywraplp
solver = pywraplp.Solver.CreateSolver('SCIP')
import numpy

Como exemplo introdutório, daremos os seguintes valores aos 'inputs' do problema.

In [3]:
n = 3
m = 8
q = 17

Para a família de variáveis binárias $e_{j,l}$, construíremos uma matriz de alocação $e$ de valores em $\{0,1\}^{M \times 3}$, para representar as variáveis binárias. Para a família de variáveis inteiras $k_{i}$ declaramos um vetor $k \in \mathbb{Z}^{n}$ Declaramos ambos como dicionários:

In [4]:
e = {}
k = {}
L = numpy.random.randint(-(q-1)/2, (q-1)/2, (m, n))

for j in range(m):
    e[j] = [solver.BoolVar('e[%i][-1]' % j),
            solver.BoolVar('e[%i][0]' % j),
            solver.BoolVar('e[%i][1]' % j)]
for i in range(n):
    k[i] = solver.IntVar(-solver.infinity(), solver.infinity(), 'k[%i]' % i)

### Restrições

Nesta seccção, apresentamos as implementações das restrições ao problema.

1. Para cada posição $j < m$ de $e$, $e[j]$ só admite um único valor;

$$ \forall_{j<m}, \quad e_{j,0} + e_{j,1} + e_{j,2} == 1 $$

In [5]:
for j in range(m):
    solver.Add(e[j][0] + e[j][1] + e[j][2] == 1)

2. Pelo menos um elemento de $e$ tem de ser não nulo;

Deste modo, o sumatório das variáveis $e_{j,1}$ não deve igualar o máximo de posições do vetor $e$, $m$.

$$ \sum_{j<m} e_{j,1} <= m-1 $$

In [6]:
solver.Add(sum([e[j][1] for j in range(m)]) <= m-1)

<ortools.linear_solver.pywraplp.Constraint; proxy of <Swig Object of type 'operations_research::MPConstraint *' at 0x000001A07FCB1020> >

3. Multiplicar o vetor $e$ pela matriz $L$ deve resultar num vetor de múltiplos de $q$.

Para cada valor de $j<m$, no máximo uma das variáveis $e_{j,0}$ e $e_{j,2}$ é igual a $1$, representando $-1$ e $1$, respetivamente. Desse modo:

$$ \forall_{j<m}, \quad e[j] == (e_{j,2} - e_{j,0}) $$

$$ \forall_{i<n}, \quad (\sum_{j<m} (e_{j,2} - e_{j,0}) * L[j][i])  == q * k[i]$$

In [7]:
for i in range(n):
    solver.Add((sum([(e[j][2] - e[j][0])*L[j][i] for j in range(m)])) == q * k[i])

### Otimização

O critério de otimização para este problma é o seguinte:

1. Maximizar o número de componentes nulas de $e$.

$$ max (\sum_{j<m} e_{j,1}) $$

In [8]:
solver.Maximize(sum([e[j][1] for j in range(m)]))

Por fim, tenta-se calcular uma solução:

In [9]:
status = solver.Solve()
if status == pywraplp.Solver.OPTIMAL:
    print(L)
    print("")
    for i in range(n):
        print(k[i].solution_value(), end = " ")
    print("")
    for j in range(m):
        for k in range(3):
            if e[j][k].solution_value():
                print(k-1, end = " ")
else:
    print(L)
    print("Não é possível resolver o problema")

[[ 4 -3 -6]
 [-6  2  2]
 [-2 -1 -5]
 [ 5  0 -2]
 [ 7  2 -2]
 [-6 -4  4]
 [ 6 -4  7]
 [-7  4 -1]]

-1.0 0.0 0.0 
0 1 0 -1 -1 0 -1 -1 

## Exemplos

Nesta seccção, experimentamos com valores progressivamente maiores de $n$, o que necessariamente aumenta a complexidade do problema, tal como, na nossa experiência, a duração e a probabilidade de não haver solução.

De modo a facilitar a testagem dos exemplos, na célula colapsada seguinte encontra-se a função $SVP(m,n,q)$. Esta função compõe todos os passos da implementação.

In [10]:
from ortools.linear_solver import pywraplp
import numpy

#  n  > 30, impossível
# |m| > 1 + |n|
# |q| > |m|

def SVP(n,m,q):
    solver = pywraplp.Solver.CreateSolver('SCIP')
    L = numpy.random.randint(-(q-1)/2, (q-1)/2, (m, n))
    e = {}
    k = {}
    #e é um vetor de tamanho m com valores inteiros -1, 0 ou 1
    for j in range(m):
        e[j] = [solver.BoolVar('e[%i][-1]' % j),
                solver.BoolVar('e[%i][0]' % j),
                solver.BoolVar('e[%i][1]' % j)]
        #1. e só pode ter um elemento por cada j
        solver.Add(e[j][0] + e[j][1] + e[j][2] == 1)
    
            
    #k é um vetor de tamanho n com valores inteiros
    for i in range(n):
        k[i] = solver.IntVar(-solver.infinity(), solver.infinity(), 'k[%i]' % i)
    
    #2. Tem de existir um elemento não nulo em e
    solver.Add(sum([e[j][1] for j in range(m)]) <= m-1)
    
    #3. Multiplicar e por L deve resultar num vetor de múltiplos de q
    for i in range(n):
        solver.Add((sum([(e[j][2] - e[j][0])*L[j][i] for j in range(m)])) == q * k[i])
    
    solver.Maximize(sum([e[j][1] for j in range(m)]))
    status = solver.Solve()
    if status == pywraplp.Solver.OPTIMAL:
        print("e:")
        print("[", end = " ")
        for j in range(m):
            for p in range(3):
                if e[j][p].solution_value():
                    print(p-1, end = " ")
        print("]", end = " ")
        print("\n\nL:")
        print(L)
        print("")
        print("k:")
        print("[", end = " ")
        for i in range(n):
            print (k[i].solution_value(),end= " ")
        print("]", end = " ")
        print("")
        return (print("Solução computada com sucesso!"))
    else:
        print(L)
        print("Não é possível resolver o problema")
        return False

### Exemplo 1

In [11]:
SVP(1, 4, 11)

e:
[ 0 0 0 -1 ] 

L:
[[-4]
 [-2]
 [-1]
 [ 0]]

k:
[ 0.0 ] 
Solução computada com sucesso!


### Exemplo 2 

In [12]:
SVP(3, 8, 11)

e:
[ 1 -1 0 0 -1 0 1 -1 ] 

L:
[[-4  4 -4]
 [-3 -1  0]
 [ 4 -2  3]
 [ 3 -2  2]
 [ 4 -1  3]
 [ 3  4  4]
 [ 3 -5 -1]
 [-2  1  3]]

k:
[ 0.0 0.0 -1.0 ] 
Solução computada com sucesso!


### Exemplo 3

In [13]:
SVP(5, 16, 37)

[[  0  -7 -13  -2   9]
 [-17  16 -15   1 -15]
 [ 16 -13   0   0   9]
 [  6  -5 -15  -7   6]
 [ 16 -14 -11   2 -10]
 [-15  -4   4   4  -2]
 [ 10  -3  14   9   7]
 [  4  -2   3 -11   5]
 [  9  -8   0  16   7]
 [ -2   3  -4   8   2]
 [ 14 -17 -11  -8  14]
 [-14   4  -1   8  16]
 [ -8 -17   4   9   6]
 [ -2  -1 -13   3 -16]
 [  7  -1 -15  -5   2]
 [-17  13   4 -13  -7]]
Não é possível resolver o problema


False

### Exemplo 4

In [14]:
SVP(7, 16, 37)

[[ -8  13   6   1 -11  -4  -2]
 [ 13  -8   8 -11  10 -13  -7]
 [  9 -17   2  -3  -6   1 -16]
 [ -4   3  -5 -13  -4   7 -13]
 [-17 -18  -7  -6  -8 -15 -15]
 [ -4 -17   9  15  -4   2   6]
 [-15 -11  16   9  -6   1 -15]
 [ -4   3   7   1 -14  15   7]
 [  7  -6  -2   9 -11   3   0]
 [  9 -14  17  -6 -15 -12 -14]
 [ 15  -5   3   4  -8 -16  -2]
 [ -9  -8  -3  13  -2  -9  13]
 [ -4   6  10  -5  -9  14 -13]
 [  8 -17   0  12  13  -3 -13]
 [  6 -15   4   1  -9 -11   7]
 [ -7  11 -12  17 -14 -15   0]]
Não é possível resolver o problema


False